### ISSUE TITLE
Issue with empty table cell (<td></td>) using ConverterExtra

### ISSUE THREAD

**Issue by francoisjacquet** [Elephant418/Markdownify#15]
Hi and thank you for this great Markdown converter!

Here is how to reproduce the issue (please note the empty `<td></td>`):

```php
$converter_extra = new Markdownify\ConverterExtra;

echo $converter_extra->parseString('<table>
<thead>
<tr>
  <th>First Header</th>
  <th>Second Header</th>
</tr>
</thead>
<tbody>
<tr>
  <td>Content Cell</td>
  <td>Content Cell</td>
</tr>
<tr>
  <td></td>
  <td>Content Cell</td>
</tr>
</tbody>
</table>');
```

The above PHP code outputs that _same_ HTML table.

Expected output:
```md
| First Header | Second Header |
| ------------ | ------------- |
| Content Cell | Content Cell |
|              | Content Cell |
```

Please note that adding a _space_ (`<td> </td>`) fixes the issue.

**Comment by tzi** [comment]
Hi @francoisjacquet!

Thanks for reporting this issue with an explicit test case :+1: 

I made a fix, it will be available in the next: [v2.1.11](https://github.com/Elephant418/Markdownify/releases/tag/v2.1.11) published few minutes ago.

If you can not update your library, you can force table conversion by setting the attribute `keepHTML` to `false`.

```php
$converter_extra->setKeepHTML(false);
```

Cheers,
Thomas.
