### ISSUE TITLE
Can't covert<img>?

### ISSUE THREAD

**Issue by xaero7** [Elephant418/Markdownify#16]
eg.`<img title="a012.gif" src="http://images/problems/a012.gif" alt="a012.gif" width="374" height="204" />`

**Comment by tzi** [comment]
Hi!

By default, Markdownify only converts HTML if it contains convertable attributes.
In your cases, `width` and `height` have no correspondence.

There is an option to force HTML conversion:

```php
$converter = new Converter();
$converter->setKeepHTML(false);
echo $converter->parseString('<img title="a012.gif" src="http://images/problems/a012.gif" alt="a012.gif" width="374" height="204" />');
```
