### ISSUE TITLE
Converter incorrectly parsing <a> elements if closing tag is preceded by a space

### ISSUE THREAD

**Issue by u-nico** [Elephant418/Markdownify#21]
#Hi all.

I might have found a bug. Here's a snippet of HTML I need to parse (using `$converter->parseString()`):

```
<p>This is a paragraph of text with <a href="https://myurl.tld">a link </a> to something awesome.</p>;
```

Note that there's a space before closing the <a> tag, which is, let's say, intended in this case.

The output that I get in Markdown is the following:

```
This is a paragraph of text with [This is a paragraph of text with][1] to something awesome.

 [1]: https://myurl.tld
````

Of course, the expected output for the code above is as follows:

```
This is a paragraph of text with [a link ][1] to something awesome.

 [1]: https://myurl.tld
```

Tested with the latest version as per writing (2.2.0). Personally I'm working around this by making sure the string I'm parsing can't have an extra space before the closing <a> tag, but I figured I'd let you know about this particular issue.

Thanks!

**Comment by tzi** [comment]
This is crazy :sweat: 

I reproduce it... Thanks a lot for reporting it.

**Comment by tzi** [comment]
It's fixed.
I packaged a new release with it: [v2.2.1](https://github.com/Elephant418/Markdownify/releases/tag/v2.2.1)

Thanks again!
