### ISSUE TITLE
links with url as anchor text not working

### ISSUE THREAD

**Issue by poppahorse** [Elephant418/Markdownify#23]
I am having issues converting the following, which seems to be because the URL is the anchor text. If I change the anchor to a non URL it works.
```
$html = '<h1>yoyo</h1><p>See <a href="https://github.com/quilljs/quill/issues/81" target="_blank">https://github.com/quilljs/quill/issues/81</a></p>';

$converter = new Markdownify\Converter;
$markdown = $converter->parseString($html);

echo $markdown;
```
This returns
```
# yoyo

See <a href="https://github.com/quilljs/quill/issues/81" target="_blank">https://github.com/quilljs/quill/issues/81</a>
```

Seems to be converting ok over here - https://domchristie.github.io/to-markdown/

Interesting, I am getting a very similar issue in another PHP library over here - https://github.com/thephpleague/html-to-markdown/issues/133

**Comment by tzi** [comment]
Hi @poppahorse!

By default, Markdownify converts HTML if it contains only convertable attributes.
In your cases, `target` has no Markdown correspondence.

There is an option to force HTML conversion:

``` php
$converter = new Converter();
$converter->setKeepHTML(false);
echo $converter->parseString('<h1>yoyo</h1><p>See <a href="https://github.com/quilljs/quill/issues/81" target="_blank">https://github.com/quilljs/quill/issues/81</a></p>');
```

Cheers,
Thomas.
