### ISSUE TITLE
Not converting tags containing attributes.

### ISSUE THREAD

**Issue by robert-groensfeld** [Elephant418/Markdownify#24]
Example:
```
$converter = new Markdownify\Converter;
echo $converter->parseString('<h1 class="something">Heading</h1>');
```
The resulting markdown should look like this: `# Heading`.
Instead, it looks like this: 
```
<h1 class="something">
  Heading
</h1>
```

**Comment by tzi** [comment]
Hi!

By default, Markdownify only converts HTML if it contains convertable attributes.
In your cases, `class` attribute has no correspondence.

There is an option to force HTML conversion:

``` php
$converter = new Converter();
$converter->setKeepHTML(false);
echo $converter->parseString('<h1 class="something">Heading</h1>');
// Output "# Heading"
```
