### ISSUE TITLE
Markdownify has deprecated constructor

### ISSUE THREAD

**Issue by samajitdas** [Elephant418/Markdownify#42]
Markdowinfy class constructor is not defined using the keyword __construct and hence gives deprecated method warning when the library is used with php 7.x version.  To fix this current constructor function(Markdownify) needs to be replaced with __construct.

**Comment by samajitdas** [comment]
May be I was using some older version of Markdownify library. Will use the latest one and comeback with my experience with that asap.

**Comment by tzi** [comment]
Hi @samajitdas 

I'm a bit surprised about this issue, I thought I've done the migration for the PHP7 support.
Which version do you use?

Cheers, 
Thomas.

**Comment by tzi** [comment]
> May be I was using some older version of Markdownify library. Will use the latest one and comeback with my experience with that asap.

OK. This seems right. If you have any problem with the migration, you can ask here.

**Comment by tzi** [comment]
Is it OK for you?
Can I close this issue?

Cheers, 
Thomas.

**Comment by samajitdas** [comment]
Yes...this issue can be closed as new version of the module seems to be working without any warning. Sorry for the confusion... :(
